version: '3'
services:
  nginx-graphql:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  #  depends_on:
  #  - app
  redis-graphql:
    image: 'redis:7.2.3'
    # networks:
    # - backend
    ports:
    - '6379:6379'
    volumes:
    - ~/mev/docker/graphql-redis/redis:/data
  # app:
  #   restart: always
  #   build: ./app
  #   working_dir: /app
  #   volumes:
  #     - ./app:/app
  #   expose:
  #     - "8080"
  #   command: mvn clean spring-boot:run